package net.buj.loader;

public class R { // Soon to become autogenerated
    private R() {}

    public static String VER = TB1-1.0.0;
    public static String VERSION_NAME = "Preview-Loader-II-" + VER;
    public static String CLIENT_DOWNLOAD_URL = "https://github.com/AlphaVerUnofficialJars/LilypadClient/releases/download/v106/lilypad_qamod_v106.jar";
    public static String SERVER_DOWNLOAD_URL = "https://github.com/AlphaVerUnofficialJars/LilypadServer/releases/download/v105/lilypad_server_v105.jar";
}
